# 1. Fase de construcción (usamos una imagen base con Java)
# Usamos Java 21, que es una versión estable y reciente compatible con Spring Boot 3.x
#FROM eclipse-temurin:17-jdk-focal


# 2. Argumento para referenciar el archivo JAR generado por Maven
# Asume que el JAR se encuentra en la carpeta 'target/' y termina en '.jar'
#ARG JAR_FILE=target/*.jar

# 3. Copia el archivo JAR compilado dentro del contenedor. 
# Se renombra a app.jar para simplificar.
#COPY ${JAR_FILE} app.jar

# 4. Define el punto de entrada (comando que se ejecuta al iniciar el contenedor)
# Esto ejecuta la aplicación Spring Boot.
#ENTRYPOINT ["java","-jar","/app.jar"]

# ETAPA 1: Compilación
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
# Copiamos el código fuente y el pom
COPY . .
# Compilamos el JAR dentro de Docker
RUN mvn clean package -DskipTests

# ETAPA 2: Ejecución
FROM eclipse-temurin:17-jdk-focal
WORKDIR /app
# Copiamos el JAR generado en la etapa anterior
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]